import {NextResponse} from "next/server";
export const dynamic="force-dynamic";
const headers={"User-Agent":"discord-profile-site/1.0","Accept":"text/html,application/xml,application/json"};
async function text(url:string){try{const r=await fetch(url,{cache:"no-store",headers});return r.ok?await r.text():""}catch{return ""}}
const fallback=()=>({url:process.env.NEXT_PUBLIC_UPLOAD_URL||"",title:process.env.NEXT_PUBLIC_UPLOAD_TITLE||"",thumbnail:process.env.NEXT_PUBLIC_UPLOAD_THUMBNAIL||"",platform:process.env.NEXT_PUBLIC_UPLOAD_PLATFORM||"YouTube",views:process.env.NEXT_PUBLIC_UPLOAD_VIEWS||"",comments:process.env.NEXT_PUBLIC_UPLOAD_COMMENTS||"",likes:process.env.NEXT_PUBLIC_UPLOAD_LIKES||"",date:process.env.NEXT_PUBLIC_UPLOAD_DATE||""});
function channelId(html:string){return html.match(/(?:"channelId"|"externalId")\s*:\s*"(UC[A-Za-z0-9_-]{20,})"/)?.[1]||html.match(/<meta[^>]+itemprop=["']channelId["'][^>]+content=["'](UC[A-Za-z0-9_-]+)["']/i)?.[1]||html.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']https:\/\/www\.youtube\.com\/channel\/(UC[A-Za-z0-9_-]+)["']/i)?.[1]||""}
function xmlValue(xml:string,tag:string){return xml.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`))?.[1]?.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/,"$1").trim()||""}
export async function GET(){
 const yt=process.env.NEXT_PUBLIC_YOUTUBE_URL||"";
 if(yt){try{let id=yt.match(/youtube\.com\/channel\/(UC[A-Za-z0-9_-]+)/)?.[1]||"";if(!id){const page=await text(yt);id=channelId(page)}if(id){const rss=await text(`https://www.youtube.com/feeds/videos.xml?channel_id=${encodeURIComponent(id)}`);const entry=rss.match(/<entry>([\s\S]*?)<\/entry>/)?.[1]||"";const videoId=xmlValue(entry,"yt:videoId");if(videoId){const title=xmlValue(entry,"title");const published=xmlValue(entry,"published");const thumb=`https://i.ytimg.com/vi/${videoId}/maxresdefault.jpg`;const video=await text(`https://www.youtube.com/watch?v=${videoId}`);const views=video.match(/(?:interactionCount|viewCount)["']?\s*[:=]\s*["'](\d+)["']/i)?.[1]||"";const likes=video.match(/(?:likeCount|likesCount)["']?\s*[:=]\s*["'](\d+)["']/i)?.[1]||"";const comments=video.match(/(?:commentCount|commentsCount)["']?\s*[:=]\s*["'](\d+)["']/i)?.[1]||"";return NextResponse.json({upload:{url:`https://www.youtube.com/watch?v=${videoId}`,title,thumbnail:thumb,platform:"YouTube",views,comments,likes,date:published.slice(0,10)}})}}}catch{}}
 return NextResponse.json({upload:fallback()},{headers:{"Cache-Control":"no-store, max-age=0"}});
}
