import {NextResponse} from "next/server";
async function api(url:string){try{const r=await fetch(url,{cache:"no-store",headers:{"User-Agent":"profile-site/1.0"}});return r.ok?await r.json():null}catch{return null}}
export const dynamic="force-dynamic";
const fallback=()=>({url:process.env.NEXT_PUBLIC_UPLOAD_URL||"",title:process.env.NEXT_PUBLIC_UPLOAD_TITLE||"",thumbnail:process.env.NEXT_PUBLIC_UPLOAD_THUMBNAIL||"",platform:process.env.NEXT_PUBLIC_UPLOAD_PLATFORM||"",views:process.env.NEXT_PUBLIC_UPLOAD_VIEWS||"",comments:process.env.NEXT_PUBLIC_UPLOAD_COMMENTS||"",likes:process.env.NEXT_PUBLIC_UPLOAD_LIKES||"",date:process.env.NEXT_PUBLIC_UPLOAD_DATE||""});
export async function GET(){
 const yt=process.env.NEXT_PUBLIC_YOUTUBE_URL||"",key=process.env.YOUTUBE_API_KEY||"";
 if(yt&&key)try{let channelId=yt.match(/youtube\.com\/channel\/(UC[A-Za-z0-9_-]+)/)?.[1]||"";const handle=yt.match(/youtube\.com\/@([A-Za-z0-9_.-]+)/)?.[1];if(handle){const r=await api(`https://www.googleapis.com/youtube/v3/channels?part=contentDetails&forHandle=${encodeURIComponent(handle)}&key=${encodeURIComponent(key)}`);channelId=r?.items?.[0]?.id||""}if(channelId){const c=await api(`https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=${channelId}&key=${encodeURIComponent(key)}`);const pl=c?.items?.[0]?.contentDetails?.relatedPlaylists?.uploads;const list=pl?await api(`https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=1&playlistId=${pl}&key=${encodeURIComponent(key)}`):null;const v=list?.items?.[0]?.snippet;const id=v?.resourceId?.videoId;if(id){const d=await api(`https://www.googleapis.com/youtube/v3/videos?part=statistics&id=${id}&key=${encodeURIComponent(key)}`);const s=d?.items?.[0]?.statistics||{};return NextResponse.json({upload:{url:`https://www.youtube.com/watch?v=${id}`,title:v.title,thumbnail:v.thumbnails?.maxres?.url||v.thumbnails?.high?.url,platform:"YouTube",views:s.viewCount||"0",comments:s.commentCount||"0",likes:s.likeCount||"0",date:v.publishedAt?.slice(0,10)||""}})}}catch{}
 const igId=process.env.INSTAGRAM_USER_ID||"",igToken=process.env.INSTAGRAM_ACCESS_TOKEN||"";
 if(igId&&igToken)try{const r=await api(`https://graph.facebook.com/v24.0/${igId}/media?fields=id,caption,media_type,media_url,thumbnail_url,permalink,timestamp,like_count,comments_count&limit=1&access_token=${encodeURIComponent(igToken)}`);const m=r?.data?.[0];if(m)return NextResponse.json({upload:{url:m.permalink,title:m.caption||"Latest Instagram upload",thumbnail:m.thumbnail_url||m.media_url,platform:"Instagram",views:"",comments:String(m.comments_count??"0"),likes:String(m.like_count??"0"),date:m.timestamp?.slice(0,10)||""}})}catch{}
 return NextResponse.json({upload:fallback()});
}
