"use client";
import {useEffect,useMemo,useState,type CSSProperties} from "react";
type Status="online"|"idle"|"dnd"|"offline";
type User={id?:string;username?:string;global_name?:string;avatar?:string|null;public_flags?:number|null;accent_color?:number|null;avatar_decoration_data?:{asset?:string|null}|null};
type Presence={data?:{discord_user?:User;discord_status?:Status;activities?:{name?:string;details?:string;state?:string;type?:number}[]};profile?:{avatarUrl?:string|null;avatarDecorationUrl?:string|null;badges?:string[];realtime?:boolean;monitored?:boolean;bannerUrl?:string|null}};
type Upload={title?:string;url?:string;thumbnail?:string;platform?:string;views?:string;comments?:string;likes?:string;date?:string};
const e={name:process.env.NEXT_PUBLIC_NAME||"Your Name",username:process.env.NEXT_PUBLIC_USERNAME||"@username",tagline:process.env.NEXT_PUBLIC_TAGLINE||"Turning ideas into code, communities & digital experiences.",bio:process.env.NEXT_PUBLIC_BIO||"Developer, creator and builder.",id:process.env.NEXT_PUBLIC_DISCORD_ID||"",discord:process.env.NEXT_PUBLIC_DISCORD_INVITE||"#",github:process.env.NEXT_PUBLIC_GITHUB_URL||"#",youtube:process.env.NEXT_PUBLIC_YOUTUBE_URL||"#",instagram:process.env.NEXT_PUBLIC_INSTAGRAM_URL||"#",twitter:process.env.NEXT_PUBLIC_TWITTER_URL||"#",age:process.env.NEXT_PUBLIC_AGE||"",role:process.env.NEXT_PUBLIC_ROLE||"DEV",location:process.env.NEXT_PUBLIC_LOCATION||"",frame:process.env.NEXT_PUBLIC_PROFILE_FRAME_URL||"",effect:process.env.NEXT_PUBLIC_PROFILE_EFFECT_URL||"",work:[1,2,3,4,5,6].map(n=>({title:process.env[`NEXT_PUBLIC_WORK_${n}_TITLE`]||["Coding & Development","Website Development","Discord Development","Minecraft Development","Automation & Tools","Creative Projects"][n-1],desc:process.env[`NEXT_PUBLIC_WORK_${n}_DESC`]||"Add your own description in the environment variables."}))};
const flags:[number,string][]=[[1,"Discord Staff"],[2,"Partner"],[4,"HypeSquad Events"],[8,"Bug Hunter"],[16,"HypeSquad Online"],[64,"HypeSquad Bravery"],[128,"HypeSquad Brilliance"],[256,"HypeSquad Balance"],[512,"Early Supporter"],[16384,"Bug Hunter Gold"],[131072,"Early Verified Bot Developer"],[262144,"Certified Moderator"],[4194304,"Active Developer"]];
const short=(x:string)=>x.includes("Active Developer")?"ACTIVE":x.includes("Early Supporter")?"EARLY":x.includes("Bravery")?"BRAVERY":x.includes("Brilliance")?"BRILLIANCE":x.includes("Balance")?"BALANCE":x.includes("Bug Hunter Gold")?"BUG+":x.includes("Bug Hunter")?"BUG":x.includes("Moderator")?"MOD":x.includes("Partner")?"PARTNER":x.includes("Staff")?"STAFF":"HYPE";
const fallbackAvatar=(id:string)=>id?`https://api.lanyard.rest/${id}.png?size=1024`:"https://cdn.discordapp.com/embed/avatars/0.png";
const ageFromId=(id:string)=>{if(!/^\d{15,22}$/.test(id))return "—";const ms=Number((BigInt(id)>>22n)+1420070400000n);return new Date(ms).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"})};
function Icon({children}:{children:string}){return <span className="textIcon">{children}</span>}
export default function ProfilePageV3(){
 const [p,setP]=useState<Presence|null>(null),[live,setLive]=useState(false),[menu,setMenu]=useState(false),[upload,setUpload]=useState<Upload|null>(null);
 const load=()=>{if(!e.id)return;fetch(`/api/discord/${e.id}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(x=>x&&setP(x)).catch(()=>{})};
 useEffect(()=>{load();const poll=setInterval(load,15000);if(!e.id)return()=>clearInterval(poll);let ws:WebSocket|null=null,beat:ReturnType<typeof setInterval>|null=null,retry:ReturnType<typeof setTimeout>|null=null,stop=false;const connect=()=>{if(stop)return;try{ws=new WebSocket("wss://api.lanyard.rest/socket");ws.onmessage=ev=>{try{const m=JSON.parse(ev.data);if(m.op===1){if(beat)clearInterval(beat);beat=setInterval(()=>{if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({op:3}))},m.d.heartbeat_interval);if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({op:2,d:{subscribe_to_id:e.id}}))}if(m.t==="INIT_STATE"&&m.d?.[e.id]){setP(q=>({data:m.d[e.id],profile:{...q?.profile,realtime:true,monitored:true}}));setLive(true)}if(m.t==="PRESENCE_UPDATE"&&m.d?.user_id===e.id){const{user_id:_,...d}=m.d;setP(q=>({data:d,profile:{...q?.profile,realtime:true,monitored:true}}));setLive(true)}}catch{}};ws.onclose=()=>{if(beat)clearInterval(beat);setLive(false);if(!stop)retry=setTimeout(connect,3000)};ws.onerror=()=>ws?.close()}catch{retry=setTimeout(connect,5000)}};connect();return()=>{stop=true;clearInterval(poll);if(beat)clearInterval(beat);if(retry)clearTimeout(retry);ws?.close()}},[]);
 const loadUpload=()=>fetch("/api/uploads",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(x=>x?.upload&&setUpload(x.upload)).catch(()=>{});
 useEffect(()=>{loadUpload();const t=setInterval(loadUpload,300000);return()=>clearInterval(t)},[]);
 const u=p?.data?.discord_user,status=p?.data?.discord_status||"offline",displayName=u?.global_name||e.name,handle=u?.username?`@${u.username}`:e.username,brandName=u?.username||e.username.replace(/^@/,"");
 const avatarUrl=p?.profile?.avatarUrl||fallbackAvatar(e.id),dec=p?.profile?.avatarDecorationUrl||(u?.avatar_decoration_data?.asset?`https://cdn.discordapp.com/avatar-decoration-presets/${u.avatar_decoration_data.asset}.png?size=512`:"");
 const badges=p?.profile?.badges?.length?p.profile.badges:(u?.public_flags?flags.filter(([b])=>(u.public_flags!&b)===b).map(x=>x[1]):[]);
 const socials=useMemo(()=>[["GitHub",e.github,"↗"],["YouTube",e.youtube,"▶"],["Instagram",e.instagram,"◎"],["X / Twitter",e.twitter,"𝕏"]] as const,[]);
 const activity=p?.data?.activities?.find(a=>a.name);
 const style={"--accent":u?.accent_color?`#${u.accent_color.toString(16).padStart(6,"0")}`:"#7c6cff"} as CSSProperties;
 const accountDate=ageFromId(e.id);
 return <main className="page v2" style={style}><div className="movingBg"><i/><i/><i/><i/><span/></div><div className="stars"/>
 <header className="topbar"><a className="brand" href="#top"><img className="brandAvatar" src={avatarUrl} alt=""/><span>{brandName}</span></a><span className="topStatus"><i className={`pulse ${status}`}/>{status.toUpperCase()}</span></header>
 <button className="menuButton" aria-label="Open menu" onClick={()=>setMenu(true)}><span/><span/><span/></button>
 {menu&&<><button className="menuShade" aria-label="Close menu" onClick={()=>setMenu(false)}/><aside className="sideMenu"><button className="closeMenu" onClick={()=>setMenu(false)}>×</button><div className="menuHead"><img src={avatarUrl} alt=""/><div><strong>{displayName}</strong><span>{handle}</span></div></div><nav><a href="#top" onClick={()=>setMenu(false)}>⌂ <span>Home</span></a><a href={e.discord} target="_blank" rel="noreferrer">◉ <span>Discord</span><b>↗</b></a><a href="#work" onClick={()=>setMenu(false)}>◈ <span>Work</span></a><a href="#uploads" onClick={()=>setMenu(false)}>▶ <span>Uploads</span></a><div className="menuLabel">SOCIALS</div>{socials.map(([name,url,icon])=><a className="socialMenu" href={url} target="_blank" rel="noreferrer" key={name} onClick={()=>setMenu(false)}><Icon>{icon}</Icon><span>{name}</span><b>↗</b></a>)}</nav></aside></>}
 <section id="top" className="hero"><div className="heroCopy"><div className="eyebrow"><i className={`pulse ${status}`}/>{status.toUpperCase()} <em>•</em> {live?"LIVE TRACKING":p?.profile?.monitored?"SYNCED / MONITORED":"NOT MONITORED"}</div><h1>{displayName}</h1><p className="heroTagline">{e.tagline}</p><p className="heroBio">{e.bio}</p><div className="actions"><a className="primary" href={e.discord} target="_blank" rel="noreferrer">◉ Discord ↗</a><a className="secondary" href="#work">Explore ↓</a></div></div>
 <div className="profileCard"><div className="cover" style={p?.profile?.bannerUrl?{backgroundImage:`linear-gradient(#0004,#08080c88),url(${p.profile.bannerUrl})`}:undefined}><div className="coverGlow"/></div><div className="avatarWrap"><img className="avatar" src={avatarUrl} alt="Discord avatar" onError={ev=>{ev.currentTarget.src=fallbackAvatar(e.id)}}/>{e.frame&&<img className="profileFrame" src={e.frame} alt=""/>}{dec&&<img className="avatarDecoration" src={dec} alt=""/>}<i className={`statusDot ${status}`}/></div><div className="profileInfo"><div className="nameLine"><h2>{displayName}</h2>{badges.slice(0,4).map(x=><span className="badge" title={x} key={x}>{short(x)}</span>)}</div><p>{handle}</p><span className="taglineSmall">{e.tagline}</span></div><div className="discordBio">{e.bio}</div>{activity&&<div className="activityCard"><div className="activityOrb"/><div><small>NOW PLAYING / ACTIVITY</small><strong>{activity.name}</strong><span>{activity.details||activity.state||"Active"}</span></div></div>}{badges.length>0&&<div className="badgesRow"><small>DISCORD BADGES</small>{badges.map(x=><span key={x} title={x}>{short(x)}</span>)}</div>}<div className="cardStats"><div><b>{e.age||"—"}</b><small>AGE</small></div><div><b>{e.role}</b><small>ROLE</small></div><div><b>{e.location||"—"}</b><small>LOCATION</small></div></div><div className="accountAge"><div><b>{accountDate}</b><span>DISCORD ACCOUNT CREATED</span></div><div><b>{p?.profile?.source||"PUBLIC PROFILE"}</b><span>DATA SOURCE</span></div></div></div></div></section>
 <section id="work" className="section"><div className="sectionTitle"><span>01</span><div><small>WHAT I DO</small><h2>Things I build.</h2></div></div><div className="skillGrid">{e.work.map((w,i)=><article className="skillCard" key={i}><div className="skillIcon"><Icon>{i===2?"◉":i===3?"▣":"&lt;/&gt;"}</Icon></div><small>{String(i+1).padStart(2,"0")}</small><h3>{w.title}</h3><p>{w.desc}</p></article>)}</div></section>
 <section id="uploads" className="section"><div className="sectionTitle"><span>02</span><div><small>LATEST UPLOAD</small><h2>Recent content.</h2></div></div>{upload?.url?<a className="uploadCard" href={upload.url} target="_blank" rel="noreferrer"><img src={upload.thumbnail||avatarUrl} alt=""/><div className="uploadInfo"><div className="platform">{upload.platform||"VIDEO"}</div><h3>{upload.title||"Latest upload"}</h3><p>{[upload.views&&`${upload.views} views`,upload.comments&&`${upload.comments} comments`,upload.likes&&`${upload.likes} likes`,upload.date].filter(Boolean).join(" · ")||"Open latest upload ↗"}</p></div><b>↗</b></a>:<div className="uploadEmpty">No public upload was found yet. Add a public YouTube channel URL to enable automatic latest-upload checking every 5 minutes.</div>}</section>
 <section id="socials" className="section"><div className="sectionTitle"><span>03</span><div><small>FIND ME</small><h2>Socials.</h2></div></div><div className="socialGrid">{socials.map(([name,url,icon])=><a className="social" href={url} target="_blank" rel="noreferrer" key={name}><span className="socialIcon"><Icon>{icon}</Icon></span><span><small>SOCIAL</small><strong>{name}</strong></span><b>↗</b></a>)}</div></section>
 <div className="bottomStatus"><div className="bottomAvatar"><img src={avatarUrl} alt=""/>{dec&&<img src={dec} alt=""/>}<i className={`statusDot ${status}`}/></div><div><strong>{displayName}</strong><span>{handle} · {live?"Live Discord tracking":status}</span></div><a href={e.discord} target="_blank" rel="noreferrer">◉</a></div></main>;
}
