"use client";
import {useCallback,useEffect,useMemo,useState,type CSSProperties} from "react";

type Status="online"|"idle"|"dnd"|"offline";
type Badge={id:string;label:string;short:string};
type User={id?:string;username?:string;global_name?:string;avatar?:string|null;banner?:string|null;public_flags?:number|null;accent_color?:number|null;avatar_decoration_data?:{asset?:string|null}|null};
type Presence={data?:{discord_user?:User;discord_status?:Status;activities?:any[];user_id?:string};profile?:{avatarUrl?:string|null;bannerUrl?:string|null;avatarDecorationUrl?:string|null;badges?:Badge[];source?:string;monitored?:boolean;realtime?:boolean;status?:Status;usernameMatches?:boolean;lastChecked?:string}};
type Upload={title?:string;url?:string;thumbnail?:string;platform?:string;views?:string;comments?:string;likes?:string;date?:string};
type Github={login:string;name:string;avatarUrl:string|null;profileUrl:string;bio:string;publicRepos:number;followers:number;following:number;company:string;location:string;repositories:{name:string;url:string;description:string;language:string;stars:number;forks:number}[]};

const cfg={
 id:process.env.NEXT_PUBLIC_DISCORD_ID?.trim()||"",name:process.env.NEXT_PUBLIC_NAME?.trim()||"Your Name",username:process.env.NEXT_PUBLIC_USERNAME?.trim()||"@username",
 tagline:process.env.NEXT_PUBLIC_TAGLINE?.trim()||"Turning ideas into code, communities and digital experiences.",bio:process.env.NEXT_PUBLIC_BIO?.trim()||"Developer, creator and builder.",
 gender:process.env.NEXT_PUBLIC_GENDER?.trim()||"",discord:process.env.NEXT_PUBLIC_DISCORD_INVITE?.trim()||"",github:process.env.NEXT_PUBLIC_GITHUB_URL?.trim()||"",
 youtube:process.env.NEXT_PUBLIC_YOUTUBE_URL?.trim()||"",instagram:process.env.NEXT_PUBLIC_INSTAGRAM_URL?.trim()||"",twitter:process.env.NEXT_PUBLIC_TWITTER_URL?.trim()||"",
 age:process.env.NEXT_PUBLIC_AGE?.trim()||"",role:process.env.NEXT_PUBLIC_ROLE?.trim()||"DEV",location:process.env.NEXT_PUBLIC_LOCATION?.trim()||"",frame:process.env.NEXT_PUBLIC_PROFILE_FRAME_URL?.trim()||""
};
const validUrl=(v:string)=>/^https?:\/\//i.test(v);
const avatarFallback=(id:string)=>id?`https://api.lanyard.rest/${id}.webp?size=1024`:"/favicon.svg";
const accountDate=(id:string)=>{try{if(!/^\d{15,22}$/.test(id))return "—";return new Date(Number((BigInt(id)>>22n)+1420070400000n)).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"})}catch{return "—"}};
const statusText=(s:Status)=>s==="dnd"?"DO NOT DISTURB":s.toUpperCase();
const workFrom=(text:string)=>{const t=text.toLowerCase();const items=[
 {keys:["website","web development","frontend","next.js","react","html","css"],title:"Web Development",desc:"Modern websites, interfaces and interactive digital experiences."},
 {keys:["discord","discord bot","community","server management"],title:"Discord Development",desc:"Bots, community systems, automation and polished Discord experiences."},
 {keys:["minecraft","plugin","minecraft server","network"],title:"Minecraft Development",desc:"Minecraft servers, plugins, systems and network experiences."},
 {keys:["automation","api","backend","system","tool","bot"],title:"Automation & Systems",desc:"Useful tools, APIs, automations and backend systems."},
 {keys:["design","ui","ux","creative","graphics"],title:"Creative & UI",desc:"Clean visual design, interfaces and creative digital experiments."},
 {keys:["ai","artificial intelligence","machine learning","technology"],title:"AI & Experiments",desc:"Exploring new technology and turning ideas into useful experiments."}
];const found=items.filter(x=>x.keys.some(k=>t.includes(k)));return found.length?found:items.slice(0,3)};
function BrandIcon({name}:{name:string}){return <span aria-hidden="true" className={`v5Brand v5-${name.toLowerCase().replace(/[^a-z]/g,"")}`}/>}
function BadgeIcon({label}:{label:string}){return <span className={`v5BadgeIcon v5Badge-${label.toLowerCase().replace(/[^a-z]/g,"")}`} title={label} aria-label={label}><span>{label.slice(0,1)}</span></span>}
function Avatar({src,decoration,frame,status,className=""}:{src:string;decoration?:string|null;frame?:string;status:Status;className?:string}){return <span className={`v5Avatar ${className}`}><img className="v5AvatarImage" src={src} onError={e=>{const el=e.currentTarget;if(!el.dataset.fallback){el.dataset.fallback="1";el.src=avatarFallback(cfg.id)}}} alt="Discord avatar"/>{frame&&validUrl(frame)&&<img className="v5AvatarFrame" src={frame} alt=""/>}{decoration&&validUrl(decoration)&&<img className="v5AvatarDecoration" src={decoration} alt=""/>}<i className={`v5StatusDot ${status}`}/></span>}

export default function ProfilePageV4(){
 const [presence,setPresence]=useState<Presence|null>(null),[realtime,setRealtime]=useState(false),[connection,setConnection]=useState("CONNECTING"),[lastSync,setLastSync]=useState("Waiting"),[menu,setMenu]=useState(false),[uploads,setUploads]=useState<{instagram?:Upload|null;youtube?:Upload|null}>({}),[github,setGithub]=useState<Github|null>(null);
 const loadProfile=useCallback(async()=>{if(!cfg.id)return;try{const r=await fetch(`/api/profile/${encodeURIComponent(cfg.id)}?username=${encodeURIComponent(cfg.username.replace(/^@/,""))}&t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error("profile");const x=await r.json();setPresence(x);setRealtime(Boolean(x.profile?.realtime));setConnection(x.profile?.realtime?"LIVE":"MONITORED");setLastSync(new Date().toLocaleTimeString())}catch{setConnection("RETRYING")}},[]);
 useEffect(()=>{loadProfile();const p=setInterval(loadProfile,15000);return()=>clearInterval(p)},[loadProfile]);
 useEffect(()=>{let stopped=false,ws:WebSocket|null=null,heartbeat:ReturnType<typeof setInterval>|null=null,retry:ReturnType<typeof setTimeout>|null=null;const connect=()=>{if(stopped||!cfg.id)return;try{setConnection("CONNECTING");ws=new WebSocket("wss://api.lanyard.rest/socket");ws.onopen=()=>setConnection("CONNECTED");ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.op===1){if(heartbeat)clearInterval(heartbeat);const ms=Math.max(10000,Number(m.d?.heartbeat_interval)||30000);heartbeat=setInterval(()=>{if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({op:3,d:null}))},ms);if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({op:2,d:{subscribe_to_id:cfg.id}}))}if(m.t==="INIT_STATE"&&m.d){const d=m.d;setPresence(q=>({data:d,profile:{...q?.profile,monitored:true,realtime:true,source:"lanyard",status:d.discord_status,lastChecked:new Date().toISOString()}}));setRealtime(true);setConnection("LIVE");setLastSync(new Date().toLocaleTimeString())}if(m.t==="PRESENCE_UPDATE"&&m.d){const d=m.d;if(!d.user_id||d.user_id===cfg.id){setPresence(q=>({data:{...q?.data,...d},profile:{...q?.profile,monitored:true,realtime:true,source:"lanyard",status:d.discord_status,lastChecked:new Date().toISOString()}}));setRealtime(true);setConnection("LIVE");setLastSync(new Date().toLocaleTimeString())}}}catch{}};ws.onclose=()=>{if(heartbeat)clearInterval(heartbeat);if(!stopped){setRealtime(false);setConnection("RECONNECTING");retry=setTimeout(connect,2500)}};ws.onerror=()=>{setConnection("RETRYING");ws?.close()}}catch{retry=setTimeout(connect,3000)}};connect();return()=>{stopped=true;if(heartbeat)clearInterval(heartbeat);if(retry)clearTimeout(retry);ws?.close()}},[]);
 useEffect(()=>{const load=()=>fetch(`/api/uploads?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(x=>x&&setUploads({instagram:x.instagram||null,youtube:x.youtube||null})).catch(()=>{});load();const t=setInterval(load,300000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!validUrl(cfg.github))return;const load=()=>fetch(`/api/github?username=${encodeURIComponent(cfg.username.replace(/^@/,""))}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(x=>x?.github&&setGithub(x.github)).catch(()=>{});load();const t=setInterval(load,300000);return()=>clearInterval(t)},[]);
 const u=presence?.data?.discord_user;const status=(presence?.data?.discord_status||presence?.profile?.status||"offline") as Status;const display=u?.global_name||cfg.name;const handle=u?.username?`@${u.username}`:cfg.username;const avatar=presence?.profile?.avatarUrl||avatarFallback(cfg.id);const decoration=presence?.profile?.avatarDecorationUrl||null;const badges=presence?.profile?.badges||[];const activity=presence?.data?.activities?.find(a=>a?.name&&a.name!=="Custom Status");
 const socialDefs=useMemo(()=>[{key:"github",name:"GitHub",url:cfg.github,icon:"github"},{key:"youtube",name:"YouTube",url:cfg.youtube,icon:"youtube"},{key:"instagram",name:"Instagram",url:cfg.instagram,icon:"instagram"},{key:"twitter",name:"X / Twitter",url:cfg.twitter,icon:"x"}].filter(x=>validUrl(x.url)),[]);
 const work=useMemo(()=>workFrom(`${cfg.bio} ${process.env.NEXT_PUBLIC_SITE_DESCRIPTION||""}`),[]);const accent=u?.accent_color?`#${u.accent_color.toString(16).padStart(6,"0")}`:"#8b7cff";const banner=presence?.profile?.bannerUrl;
 return <main className="profileV5" style={{"--v5-accent":accent} as CSSProperties}>
  <div className="v5Background"><span/><span/><span/><span/></div>
  <header className="v5Top"><a href="#home" className="v5Identity"><Avatar src={avatar} decoration={decoration} frame={cfg.frame} status={status} className="v5TinyAvatar"/><span><b>{handle.replace(/^@/,"")}</b><small>{realtime?"LIVE PRESENCE":"DISCORD PROFILE"}</small></span></a><div className="v5Connection"><i className={`v5StatusDot ${status}`}/><b>{statusText(status)}</b><span>{realtime?"LIVE REALTIME":connection}</span><em>{lastSync}</em></div><button className="v5MenuButton" onClick={()=>setMenu(true)} aria-label="Open navigation"><span/><span/><span/></button></header>
  {menu&&<><button className="v5Backdrop" onClick={()=>setMenu(false)} aria-label="Close navigation"/><aside className="v5Drawer"><button className="v5Close" onClick={()=>setMenu(false)} aria-label="Close">×</button><div className="v5DrawerUser"><Avatar src={avatar} decoration={decoration} frame={cfg.frame} status={status}/><div><b>{display}</b><span>{handle}</span></div></div><small className="v5DrawerLabel">NAVIGATION</small>{[["01","Home","home"],["02","Work","work"],["03","GitHub","github"],["04","Uploads","uploads"],["05","Socials","socials"]].map(([n,label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}><span>{n}</span><b>{label}</b></a>)}{cfg.discord&&validUrl(cfg.discord)&&<a href={cfg.discord} target="_blank" rel="noreferrer"><span>06</span><b>Discord</b><strong>OPEN</strong></a>}{socialDefs.length>0&&<><small className="v5DrawerLabel">CONNECTED</small>{socialDefs.map(s=><a key={s.key} href={s.url} target="_blank" rel="noreferrer"><BrandIcon name={s.icon}/><b>{s.name}</b><strong>OPEN</strong></a>)}</>}</aside></>}

  <section id="home" className="v5Hero"><div className="v5HeroCopy"><div className="v5Eyebrow"><i className={`v5StatusDot ${status}`}/>{realtime?"LIVE DISCORD PRESENCE":"DISCORD PROFILE"}<span>/</span>{presence?.profile?.source||"PUBLIC DATA"}</div><h1>{display}</h1><p className="v5Handle">{handle}</p><p className="v5Tagline">{cfg.tagline}</p><p className="v5Bio">{cfg.bio}</p><div className="v5Actions">{cfg.discord&&validUrl(cfg.discord)&&<a className="v5Primary" href={cfg.discord} target="_blank" rel="noreferrer"><BrandIcon name="discord"/>Discord <span>↗</span></a>}<a className="v5Secondary" href="#work">Explore profile <span>↓</span></a></div><div className="v5Facts"><div><b>{realtime?"LIVE":connection}</b><span>Presence</span></div><div><b>{badges.length}</b><span>Badges</span></div><div><b>{work.length}</b><span>Skills</span></div><div><b>{accountDate(cfg.id)}</b><span>Account created</span></div></div></div>
   <article className="v5Card">{banner?<div className="v5Banner" style={{backgroundImage:`linear-gradient(180deg,rgba(0,0,0,.12),rgba(8,8,14,.92)),url(${banner})`}}/>:<div className="v5Banner v5BannerEmpty"/>}<div className="v5CardAvatar"><Avatar src={avatar} decoration={decoration} frame={cfg.frame} status={status}/></div><div className="v5CardBody"><div className="v5NameRow"><div><h2>{display}</h2><p>{handle}</p></div><div className="v5BadgeRow">{badges.slice(0,5).map(b=><BadgeIcon key={b.id} label={b.label}/>)}</div></div><div className="v5CardBio">{cfg.bio}</div>{activity&&<div className="v5Activity"><span className="v5ActivityMark">A</span><div><small>ACTIVE NOW</small><b>{activity.name}</b><span>{activity.details||activity.state||"Discord activity"}</span></div><em>{realtime?"LIVE":"SYNC"}</em></div>}<div className="v5BadgeBox"><div><small>DISCORD BADGES</small><b>{badges.length}</b></div>{badges.length?<div className="v5BadgeList">{badges.map(b=><span key={b.id}><BadgeIcon label={b.label}/>{b.label}</span>)}</div>:<p>Public badge data is unavailable from the current Discord profile providers.</p>}</div><div className="v5MetaGrid"><div><small>ROLE</small><b>{cfg.role||"—"}</b></div><div><small>AGE</small><b>{cfg.age||"—"}</b></div><div><small>GENDER</small><b>{cfg.gender||"—"}</b></div><div><small>LOCATION</small><b>{cfg.location||"—"}</b></div></div></div></article>
  </section>

  {github&&<section id="github" className="v5Section"><div className="v5SectionTitle"><small>02 / GITHUB PROFILE</small><h2>Open source work.</h2><p>Live public profile data from the connected GitHub account.</p></div><article className="v5GithubCard"><div className="v5GithubHead"><img src={github.avatarUrl||avatar} alt="GitHub avatar"/><div><small>CONNECTED GITHUB</small><h3>{github.name}</h3><a href={github.profileUrl} target="_blank" rel="noreferrer">@{github.login} ↗</a></div><BrandIcon name="github"/></div>{github.bio&&<p className="v5GithubBio">{github.bio}</p>}<div className="v5GithubStats"><div><b>{github.publicRepos}</b><span>Repositories</span></div><div><b>{github.followers}</b><span>Followers</span></div><div><b>{github.following}</b><span>Following</span></div></div>{github.repositories.length>0&&<div className="v5RepoGrid">{github.repositories.map(r=><a key={r.url} href={r.url} target="_blank" rel="noreferrer"><div><b>{r.name}</b><span>{r.description}</span></div><em>{r.language||"Repo"} · ★ {r.stars}</em></a>)}</div>}</article></section>}

  <section id="work" className="v5Section"><div className="v5SectionTitle"><small>03 / WHAT I DO</small><h2>Things I build.</h2><p>Work categories are generated from the profile bio and site description.</p></div><div className="v5WorkGrid">{work.map((w,i)=><article key={w.title}><span>0{i+1}</span><h3>{w.title}</h3><p>{w.desc}</p></article>)}</div></section>

  <section id="uploads" className="v5Section"><div className="v5SectionTitle"><small>04 / LATEST UPLOADS</small><h2>Recent content.</h2><p>Connected platforms are checked automatically and refreshed every five minutes.</p></div><div className="v5UploadGrid">{([['youtube','YouTube',uploads.youtube,'youtube'],['instagram','Instagram',uploads.instagram,'instagram']] as const).filter(([key])=>key==='youtube'?validUrl(cfg.youtube):validUrl(cfg.instagram)).map(([key,label,item,icon])=><article className="v5UploadCard" key={key}><div className="v5SectionIcon"><BrandIcon name={icon}/><span>{label}</span></div>{item?.url?<a href={item.url} target="_blank" rel="noreferrer"><img src={item.thumbnail||avatar} alt=""/><div><small>{item.platform||label}</small><h3>{item.title||"Latest upload"}</h3><p>{[item.views&&`${item.views} views`,item.likes&&`${item.likes} likes`,item.comments&&`${item.comments} comments`,item.date].filter(Boolean).join(" · ")||"Open content ↗"}</p></div><b>↗</b></a>:<div className="v5Empty">No public upload is available yet. The connector will keep checking automatically.</div>}</article>)}</div></section>

  {socialDefs.length>0&&<section id="socials" className="v5Section"><div className="v5SectionTitle"><small>05 / CONNECTED ACCOUNTS</small><h2>Find me.</h2><p>Only accounts with a valid URL variable are shown.</p></div><div className="v5SocialGrid">{socialDefs.map(s=><a className="v5SocialCard" key={s.key} href={s.url} target="_blank" rel="noreferrer"><span className="v5SocialIcon"><BrandIcon name={s.icon}/></span><div><small>CONNECTED ACCOUNT</small><strong>{s.name}</strong><span>{s.url.replace(/^https?:\/\//i,"").replace(/\/$/,"")}</span></div><b>↗</b></a>)}</div></section>}

  <footer className="v5Footer"><span>{display} / Personal profile</span><span>{realtime?"Realtime presence":"Public profile data"} / Updated {lastSync}</span></footer>
  <div className="v5Bottom"><Avatar src={avatar} decoration={decoration} frame={cfg.frame} status={status} className="v5BottomAvatar"/><div><b>{display}</b><span>{handle} / {statusText(status)}</span></div>{cfg.discord&&validUrl(cfg.discord)&&<a href={cfg.discord} target="_blank" rel="noreferrer" aria-label="Discord"><BrandIcon name="discord"/></a>}</div>
 </main>;
}
