"use client";
import {useEffect,useMemo,useState,type CSSProperties} from "react";

type Status="online"|"idle"|"dnd"|"offline";
type User={id?:string;username?:string;global_name?:string;avatar?:string|null;public_flags?:number|null;accent_color?:number|null;avatar_decoration_data?:{asset?:string|null}|null};
type Presence={data?:{discord_user?:User;discord_status?:Status;activities?:any[]};profile?:{avatarUrl?:string|null;bannerUrl?:string|null;avatarDecorationUrl?:string|null;badges?:string[];source?:string;monitored?:boolean;realtime?:boolean}};
type Upload={title?:string;url?:string;thumbnail?:string;platform?:string;views?:string;comments?:string;likes?:string;date?:string};
const cfg={id:process.env.NEXT_PUBLIC_DISCORD_ID||"",name:process.env.NEXT_PUBLIC_NAME||"Your Name",username:process.env.NEXT_PUBLIC_USERNAME||"@username",tagline:process.env.NEXT_PUBLIC_TAGLINE||"Turning ideas into code, communities & digital experiences.",bio:process.env.NEXT_PUBLIC_BIO||"Developer, creator and builder.",discord:process.env.NEXT_PUBLIC_DISCORD_INVITE||"#",github:process.env.NEXT_PUBLIC_GITHUB_URL||"#",youtube:process.env.NEXT_PUBLIC_YOUTUBE_URL||"#",instagram:process.env.NEXT_PUBLIC_INSTAGRAM_URL||"#",twitter:process.env.NEXT_PUBLIC_TWITTER_URL||"#",age:process.env.NEXT_PUBLIC_AGE||"",role:process.env.NEXT_PUBLIC_ROLE||"DEV",location:process.env.NEXT_PUBLIC_LOCATION||"",frame:process.env.NEXT_PUBLIC_PROFILE_FRAME_URL||"",work:[1,2,3,4,5,6].map(n=>({title:process.env[`NEXT_PUBLIC_WORK_${n}_TITLE`]||["Coding & Development","Website Development","Discord Development","Minecraft Development","Automation & Tools","Creative Projects"][n-1],desc:process.env[`NEXT_PUBLIC_WORK_${n}_DESC`]||"Add a description in your environment variables."}))};
const flags:[number,string][]=[[1,"Discord Staff"],[2,"Partner"],[4,"HypeSquad Events"],[8,"Bug Hunter"],[16,"HypeSquad Online"],[64,"HypeSquad Bravery"],[128,"HypeSquad Brilliance"],[256,"HypeSquad Balance"],[512,"Early Supporter"],[16384,"Bug Hunter Gold"],[131072,"Early Verified Bot Developer"],[262144,"Certified Moderator"],[4194304,"Active Developer"]];
const short=(x:string)=>x.includes("Active Developer")?"ACTIVE":x.includes("Early Supporter")?"EARLY":x.includes("Bravery")?"BRAVE":x.includes("Brilliance")?"BRILLIANT":x.includes("Balance")?"BALANCE":x.includes("Bug Hunter Gold")?"BUG+":x.includes("Bug Hunter")?"BUG":x.includes("Moderator")?"MOD":x.includes("Partner")?"PARTNER":x.includes("Staff")?"STAFF":"HYPE";
const fallback=(id:string)=>id?`https://api.lanyard.rest/${id}.png?size=1024`:"https://cdn.discordapp.com/embed/avatars/0.png";
const accountDate=(id:string)=>{try{if(!/^\d{15,22}$/.test(id))return "—";return new Date(Number((BigInt(id)>>22n)+1420070400000n)).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"})}catch{return "—"}};
function Icon({children}:{children:string}){return <span className="iconText">{children}</span>}
function statusLabel(s:Status){return s==="dnd"?"DO NOT DISTURB":s.toUpperCase()}
export default function ProfilePageV4(){
 const [presence,setPresence]=useState<Presence|null>(null),[live,setLive]=useState(false),[menu,setMenu]=useState(false),[upload,setUpload]=useState<Upload|null>(null),[lastSeen,setLastSeen]=useState("Waiting for realtime presence…");
 const loadProfile=()=>{if(!cfg.id)return;fetch(`/api/profile/${cfg.id}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(x=>x&&setPresence(x)).catch(()=>{})};
 useEffect(()=>{loadProfile();const poll=setInterval(loadProfile,15000);if(!cfg.id)return()=>clearInterval(poll);let stopped=false,lws:WebSocket|null=null,beat:ReturnType<typeof setInterval>|null=null,retry:ReturnType<typeof setTimeout>|null=null;const connect=()=>{if(stopped)return;try{lws=new WebSocket("wss://api.lanyard.rest/socket");lws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.op===1){if(beat)clearInterval(beat);beat=setInterval(()=>{if(lws?.readyState===WebSocket.OPEN)lws.send(JSON.stringify({op:3,d:{}}))},Math.max(10000,m.d?.heartbeat_interval||30000));if(lws.readyState===WebSocket.OPEN)lws.send(JSON.stringify({op:2,d:{subscribe_to_ids:[cfg.id]}}))}if(m.t==="INIT_STATE"){const d=m.d?.[cfg.id];if(d){setPresence(q=>({data:d,profile:{...q?.profile,monitored:true,realtime:true,source:"lanyard"}}));setLive(true);setLastSeen("Realtime WebSocket connected")}}if(m.t==="PRESENCE_UPDATE"){const d=m.d?.user_id===cfg.id?m.d:null;if(d){setPresence(q=>({data:d,profile:{...q?.profile,monitored:true,realtime:true,source:"lanyard"}}));setLive(true);setLastSeen(new Date().toLocaleTimeString())}}}catch{}};lws.onclose=()=>{if(beat)clearInterval(beat);setLive(false);if(!stopped)retry=setTimeout(connect,3000)};lws.onerror=()=>lws?.close()}catch{retry=setTimeout(connect,5000)}};connect();return()=>{stopped=true;clearInterval(poll);if(beat)clearInterval(beat);if(retry)clearTimeout(retry);lws?.close()}},[]);
 useEffect(()=>{const load=()=>fetch("/api/uploads",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(x=>x?.upload&&setUpload(x.upload)).catch(()=>{});load();const t=setInterval(load,300000);return()=>clearInterval(t)},[]);
 const u=presence?.data?.discord_user,status=presence?.data?.discord_status||"offline",display=u?.global_name||cfg.name,handle=u?.username?`@${u.username}`:cfg.username,brand=u?.username||cfg.username.replace(/^@/,"");
 const avatar=presence?.profile?.avatarUrl||fallback(cfg.id),dec=presence?.profile?.avatarDecorationUrl||(u?.avatar_decoration_data?.asset?`https://cdn.discordapp.com/avatar-decoration-presets/${u.avatar_decoration_data.asset}.png?size=512`:"");
 const badges=presence?.profile?.badges?.length?presence.profile.badges:(u?.public_flags?flags.filter(([b])=>(u.public_flags!&b)===b).map(x=>x[1]):[]),activity=presence?.data?.activities?.find(a=>a?.name&&a.name!=="Custom Status");
 const socials=useMemo(()=>[["GitHub",cfg.github,"GH"],["YouTube",cfg.youtube,"YT"],["Instagram",cfg.instagram,"IG"],["X / Twitter",cfg.twitter,"X"]] as const,[]);
 const accent=u?.accent_color?`#${u.accent_color.toString(16).padStart(6,"0")}`:"#8b7cff",cover=presence?.profile?.bannerUrl?{backgroundImage:`linear-gradient(180deg,#0003,#08080cee),url(${presence.profile.bannerUrl})`}:undefined;
 return <main className="rebuildPage" style={{"--accent":accent} as CSSProperties}><div className="aurora"><i/><i/><i/><i/></div><div className="gridNoise"/>
 <header className="rebuildTop"><a className="identity" href="#home"><img src={avatar} onError={e=>{e.currentTarget.src=fallback(cfg.id)}} alt=""/><span>{brand}</span><b className={`liveDot ${status}`}/></a><div className="tracking"><i className={`liveDot ${status}`}/>{live?"LIVE":statusLabel(status)} <span>•</span> {live?lastSeen:(presence?.profile?.monitored?"MONITORED":"NOT MONITORED")}</div></header>
 <button className="drawerTrigger" onClick={()=>setMenu(true)} aria-label="Open navigation"><span/><span/><span/></button>
 {menu&&<><button className="drawerBackdrop" onClick={()=>setMenu(false)} aria-label="Close navigation"/><aside className="drawer"><button className="drawerClose" onClick={()=>setMenu(false)}>×</button><div className="drawerProfile"><img src={avatar} alt=""/><div><strong>{display}</strong><span>{handle}</span></div></div><div className="drawerTitle">NAVIGATION</div><nav><a href="#home" onClick={()=>setMenu(false)}><Icon>⌂</Icon><span>Home</span></a><a href={cfg.discord} target="_blank" rel="noreferrer"><Icon>◉</Icon><span>Discord</span><b>↗</b></a><a href="#work" onClick={()=>setMenu(false)}><Icon>◆</Icon><span>Work</span></a><a href="#uploads" onClick={()=>setMenu(false)}><Icon>▶</Icon><span>Uploads</span></a><div className="drawerTitle">SOCIALS</div>{socials.map(([n,url,ic])=><a key={n} href={url} target="_blank" rel="noreferrer"><Icon>{ic}</Icon><span>{n}</span><b>↗</b></a>)}</nav></aside></>}
 <section id="home" className="rebuildHero"><div className="heroText"><div className="liveBadge"><i className={`liveDot ${status}`}/>{live?"LIVE DISCORD PRESENCE":"DISCORD PROFILE"}<span>•</span>{presence?.profile?.source||"SYNC"}</div><h1>{display}</h1><div className="handle">{handle}</div><p className="tagline">{cfg.tagline}</p><p className="bio">{cfg.bio}</p><div className="heroButtons"><a className="btnBright" href={cfg.discord} target="_blank" rel="noreferrer">Discord ↗</a><a className="btnGlass" href="#work">Explore profile ↓</a></div><div className="tinyFacts"><span><b>{live?"LIVE":"SYNC"}</b> Presence</span><span><b>{badges.length}</b> Badges</span><span><b>{cfg.work.length}</b> Skills</span></div></div>
 <article className="discordCard"><div className="cardBanner" style={cover}><div className="bannerGlow"/><span className="bannerTag">DISCORD PROFILE</span></div><div className="avatarDock"><img className="mainAvatar" src={avatar} onError={e=>{e.currentTarget.src=fallback(cfg.id)}} alt="Discord avatar"/>{cfg.frame&&<img className="frame" src={cfg.frame} alt=""/>}{dec&&<img className="decoration" src={dec} alt=""/>}<i className={`cardStatus ${status}`}/></div><div className="cardBody"><div className="cardName"><h2>{display}</h2>{badges.slice(0,4).map(x=><span key={x} title={x}>{short(x)}</span>)}</div><p>{handle}</p><div className="cardBio">{cfg.bio}</div>{activity&&<div className="nowPlaying"><div className="activityIcon">♪</div><div><small>ACTIVE NOW</small><strong>{activity.name}</strong><span>{activity.details||activity.state||"Discord activity"}</span></div><em>{live?"LIVE":"SYNC"}</em></div>}{badges.length>0&&<div className="badgeBox"><small>BADGES</small><div>{badges.map(x=><span key={x}>{short(x)}</span>)}</div></div>}<div className="stats"><div><b>{cfg.age||"—"}</b><span>AGE</span></div><div><b>{cfg.role}</b><span>ROLE</span></div><div><b>{cfg.location||"—"}</b><span>LOCATION</span></div></div><div className="created"><div><b>{accountDate(cfg.id)}</b><span>ACCOUNT CREATED</span></div><div><b>{live?"REALTIME":"PUBLIC"}</b><span>DATA MODE</span></div></div></div></article></section>
 <section id="work" className="rebuildSection"><div className="sectionHead"><span>01</span><div><small>WHAT I DO</small><h2>Things I build.</h2></div></div><div className="workGrid">{cfg.work.map((w,i)=><article className="workCard" key={i}><small>{String(i+1).padStart(2,"0")}</small><div className="workIcon">{i===2?"DIS":i===3?"MC":"⌁"}</div><h3>{w.title}</h3><p>{w.desc}</p></article>)}</div></section>
 <section id="uploads" className="rebuildSection"><div className="sectionHead"><span>02</span><div><small>LATEST UPLOAD</small><h2>Recent content.</h2></div></div>{upload?.url?<a className="upload" href={upload.url} target="_blank" rel="noreferrer"><img src={upload.thumbnail||avatar} alt=""/><div><small>{upload.platform||"CONTENT"}</small><h3>{upload.title||"Latest upload"}</h3><p>{[upload.views&&`${upload.views} views`,upload.comments&&`${upload.comments} comments`,upload.likes&&`${upload.likes} likes`,upload.date].filter(Boolean).join(" · ")||"Open content ↗"}</p></div><b>↗</b></a>:<div className="empty">No public upload is available yet. The site checks the configured public channel every 5 minutes.</div>}</section>
 <section id="socials" className="rebuildSection"><div className="sectionHead"><span>03</span><div><small>FIND ME</small><h2>Socials.</h2></div></div><div className="socials">{socials.map(([n,url,ic])=><a className="socialCard" key={n} href={url} target="_blank" rel="noreferrer"><span>{ic}</span><div><small>SOCIAL</small><strong>{n}</strong></div><b>↗</b></a>)}</div></section>
 <footer><span>Built around the Discord profile • {display}</span><span>Live presence: {live?"connected":"waiting for monitored presence"}</span></footer><div className="bottomBar"><div className="bottomPic"><img src={avatar} alt=""/>{dec&&<img src={dec} alt=""/>}<i className={`liveDot ${status}`}/></div><div className="bottomInfo"><strong>{display}</strong><span>{handle} • {live?"Live Discord tracking":"Presence synced"}</span></div><a href={cfg.discord} target="_blank" rel="noreferrer">◉</a></div>
 </main>;
}
