"use client";

import { useEffect, useMemo, useState } from "react";

type Activity = { name?: string; type?: number; details?: string | null; state?: string | null; assets?: { large_image?: string; large_text?: string } };
type DiscordUser = { id: string; username?: string; global_name?: string | null; avatar?: string | null; banner?: string | null; accent_color?: number | null; public_flags?: number | null; avatar_decoration_data?: { asset?: string | null } | null };
type Presence = { data?: { discord_user?: DiscordUser; discord_status?: "online" | "idle" | "dnd" | "offline"; activities?: Activity[] } };

const env = {
  name: process.env.NEXT_PUBLIC_NAME || "Aaravg", username: process.env.NEXT_PUBLIC_USERNAME || "@aarav",
  tagline: process.env.NEXT_PUBLIC_TAGLINE || "Turning ideas into code, communities & digital experiences.",
  bio: process.env.NEXT_PUBLIC_BIO || "Coder • Website Developer • Discord Developer • Minecraft Developer • Discord Server Cloner",
  discordId: process.env.NEXT_PUBLIC_DISCORD_ID || "", invite: process.env.NEXT_PUBLIC_DISCORD_INVITE || "#",
  github: process.env.NEXT_PUBLIC_GITHUB_URL || "#", youtube: process.env.NEXT_PUBLIC_YOUTUBE_URL || "#", instagram: process.env.NEXT_PUBLIC_INSTAGRAM_URL || "#", twitter: process.env.NEXT_PUBLIC_TWITTER_URL || "#",
  age: process.env.NEXT_PUBLIC_AGE || "20", role: process.env.NEXT_PUBLIC_ROLE || "DEV", gender: process.env.NEXT_PUBLIC_GENDER || "Developer", location: process.env.NEXT_PUBLIC_LOCATION || "India",
  profileFrame: process.env.NEXT_PUBLIC_PROFILE_FRAME_URL || "",
};
const labels = { online: "Online", idle: "Idle", dnd: "Do Not Disturb", offline: "Offline" } as const;
function discordAvatar(id: string, hash?: string | null) { if (hash) return `https://cdn.discordapp.com/avatars/${id}/${hash}.png?size=1024`; if (id) return `https://api.lanyard.rest/${id}.png?size=1024`; return "https://cdn.discordapp.com/embed/avatars/0.png"; }
function discordBanner(id: string, hash?: string | null) { return hash ? `https://cdn.discordapp.com/banners/${id}/${hash}.png?size=2048` : ""; }
function discordDecoration(asset?: string | null) { return asset ? `https://cdn.discordapp.com/avatar-decoration-presets/${asset}.png?size=512` : ""; }
function discordCreatedAt(id: string) { try { const snowflake = BigInt(id); const ms = Number((snowflake >> 22n) + 1420070400000n); const date = new Date(ms); return Number.isFinite(date.getTime()) ? date : null; } catch { return null; } }
const FLAG_BADGES: [number,string,string][] = [[1,"Discord Staff","STAFF"],[2,"Partner","PARTNER"],[4,"HypeSquad Events","HYPE"],[8,"Bug Hunter","BUG"],[64,"HypeSquad Bravery","BRAVERY"],[128,"HypeSquad Brilliance","BRILLIANCE"],[256,"HypeSquad Balance","BALANCE"],[512,"Early Supporter","EARLY"],[16384,"Bug Hunter Gold","BUG+"],[131072,"Early Verified Bot Developer","DEV"],[262144,"Certified Moderator","MOD"],[4194304,"Active Developer","ACTIVE"]];
function badges(flags?: number | null) { if (!flags) return []; return FLAG_BADGES.filter(([bit]) => (flags & bit) === bit).map(([,title,short]) => ({title,short})); }
function Icon({ kind }: { kind: "github"|"youtube"|"instagram"|"x"|"discord"|"code"|"minecraft" }) { const paths = {
  github:<path d="M12 .7a11.3 11.3 0 0 0-3.57 22c.57.1.78-.25.78-.55v-2.13c-3.17.69-3.84-1.34-3.84-1.34-.52-1.32-1.27-1.67-1.27-1.67-1.04-.71.08-.7.08-.7 1.15.08 1.76 1.18 1.76 1.18 1.02 1.75 2.68 1.25 3.33.96.1-.74.4-1.25.73-1.54-2.53-.29-5.19-1.27-5.19-5.65 0-1.25.45-2.27 1.18-3.07-.12-.29-.51-1.46.11-3.04 0 0 .96-.31 3.14 1.17A10.9 10.9 0 0 1 12 5.96c.97 0 1.94.13 2.85.38 2.18-1.48 3.14-1.17 3.14-1.17.62 1.58.23 2.75.11 3.04.73.8 1.18 1.82 1.18 3.07 0 4.39-2.66 5.36-5.2 5.64.41.36.78 1.08.78 2.18v3.23c0 .3.21.66.79.55A11.3 11.3 0 0 0 12 .7Z"/>,
  youtube:<path d="M23.5 6.2a3 3 0 0 0-2.1-2.12C19.55 3.5 12 3.5 12 3.5s-7.55 0-9.4.58A3 3 0 0 0 .5 6.2 31.2 31.2 0 0 0 0 12a31.2 31.2 0 0 0 .5 5.8 3 3 0 0 0 2.1 2.12c1.85.58 9.4.58 9.4.58s7.55 0 9.4-.58a3 3 0 0 0 2.1-2.12A31.2 31.2 0 0 0 24 12a31.2 31.2 0 0 0-.5-5.8ZM9.6 15.9V8.1l6.5 3.9-6.5 3.9Z"/>,
  instagram:<><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></>, x:<path d="m4 4 16 16M20 4 4 20"/>,
  discord:<path d="M19.5 5.2A16 16 0 0 0 15.6 4l-.5 1a14.6 14.6 0 0 0-6.2 0l-.5-1a16 16 0 0 0-3.9 1.2C2 8.1 1.4 12.9 1.7 17.6a16 16 0 0 0 4.8 2.4l1.2-1.7a10 10 0 0 1-1.9-.9l.5-.4c3.7 1.7 7.7 1.7 11.4 0l.5.4a12 12 0 0 1-1.9.9l1.2 1.7a16 16 0 0 0 4.8-2.4c.4-5.5-.7-10.2-2.8-12.4ZM8.9 15.2c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2Zm6.2 0c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2Z"/>,
  code:<path d="m8 7-5 5 5 5M16 7l5 5-5 5M14 3l-4 18"/>, minecraft:<path d="M4 4h16v16H4zM7 7h4v4H7zm6 0h4v4h-4zM7 13h4v4H7zm6 0h4v4h-4z"/>
 }; return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[kind]}</svg>; }

export default function ProfilePage() {
 const [presence,setPresence]=useState<Presence|null>(null); const [copied,setCopied]=useState(false); const [views,setViews]=useState(1284); const [now,setNow]=useState(Date.now());
 useEffect(()=>{const load=async()=>{if(!env.discordId)return;try{const r=await fetch(`/api/discord/${env.discordId}`,{cache:"no-store"});if(r.ok)setPresence(await r.json());}catch{}};load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(t)},[]);
 useEffect(()=>{try{const k="aaravg-profile-views",n=Number(localStorage.getItem(k)||"1284")+1;localStorage.setItem(k,String(n));setViews(n)}catch{}},[]);
 const user=presence?.data?.discord_user,status=presence?.data?.discord_status||"offline",activity=(presence?.data?.activities||[]).find(a=>a.type!==4),name=user?.global_name||user?.username||env.name,username=user?.username?`@${user.username}`:env.username,accent=user?.accent_color?`#${user.accent_color.toString(16).padStart(6,"0")}`:"#7c6cff",image=discordAvatar(env.discordId,user?.avatar),bannerImage=discordBanner(env.discordId,user?.banner),decorationImage=discordDecoration(user?.avatar_decoration_data?.asset),earnedBadges=badges(user?.public_flags),createdAt=discordCreatedAt(env.discordId),accountDays=createdAt?Math.max(0,Math.floor((now-createdAt.getTime())/86400000)):null;
 const socials=useMemo(()=>[["GitHub",env.github,"github"],["YouTube",env.youtube,"youtube"],["Instagram",env.instagram,"instagram"],["X / Twitter",env.twitter,"x"]] as const,[]); const copy=async()=>{if(!env.discordId)return;try{await navigator.clipboard.writeText(env.discordId);setCopied(true);setTimeout(()=>setCopied(false),1400)}catch{}};
 return <main className="page" style={{"--accent":accent} as React.CSSProperties}>
  <div className="movingBg"><i/><i/><i/><i/><span/></div><div className="stars"/><div className="grain"/>
  <nav className="nav"><a className="brand" href="#top"><b>A</b> aaravg</a><div className="navLinks"><a href="#about">About</a><a href="#skills">Skills</a><a href="#socials">Socials</a></div><a className="navDiscord" href={env.invite} target="_blank" rel="noreferrer"><Icon kind="discord"/> Discord</a></nav>
  <section id="top" className="hero"><div className="heroCopy"><div className="eyebrow"><span className={`pulse ${status}`}/>{labels[status].toUpperCase()} <em>•</em> LIVE PROFILE</div><h1>Code.<br/><span>Create.</span><br/>Connect.</h1><p className="heroTagline">{env.tagline}</p><p className="heroBio">{env.bio}. Building websites, Discord communities, Minecraft servers and digital experiences.</p><div className="actions"><a className="primary" href={env.invite} target="_blank" rel="noreferrer"><Icon kind="discord"/> Join my Discord ↗</a><a className="secondary" href="#about">Explore ↓</a></div><div className="heroMeta"><span><b>{views.toLocaleString()}</b> views</span><span>•</span><span>{env.age} · {env.location}</span></div></div>
   <div className="profileCard" style={{"--card-accent":accent} as React.CSSProperties}><div className="cardTop"><span className="livePill"><i className={`statusMini ${status}`}/>{labels[status]}</span><span className="orbMini">◈ ORBS <small>not public</small></span></div><div className="cover" style={bannerImage?{backgroundImage:`linear-gradient(180deg,#0000,#08080b),url(${bannerImage})`}:undefined}><div className="coverGlow"/><div className="scanline"/></div><div className="avatarArea"><div className="avatarWrap"> <img className="avatar" src={image} alt="Discord avatar" onError={e=>{const el=e.currentTarget;if(!el.dataset.fallback){el.dataset.fallback="1";el.src="https://cdn.discordapp.com/embed/avatars/0.png"}}}/>{env.profileFrame&&<img className="profileFrame" src={env.profileFrame} alt=""/>}{decorationImage&&<img className="avatarDecoration" src={decorationImage} alt="Discord avatar decoration"/>}<span className={`statusDot ${status}`}/></div></div><div className="profileInfo"><div className="nameLine"><h2>{name}</h2>{earnedBadges.slice(0,5).map(b=><span key={b.title} className="badge" title={b.title}>{b.short}</span>)}<span className="verified">✦</span></div><p>{username}</p><div className="profileTagline">{env.tagline}</div></div><div className="profileEffect unavailable"><span>PROFILE EFFECT</span><small>Not available from Discord&apos;s public User API</small></div><div className="discordBio"><span className="bioIcon">✦</span><span>{env.bio}</span></div>{earnedBadges.length>0&&<div className="badgesRow"><small>DISCORD BADGES</small><div>{earnedBadges.map(b=><span key={b.title} title={b.title}>{b.short}</span>)}</div></div>}{activity&&<div className="activityCard"><div className="activityOrb"/><div><small>ACTIVE NOW</small><strong>{activity.name||"Discord activity"}</strong><span>{activity.details||activity.state||"Currently active"}</span></div></div>}<div className="cardStats"><div><b>{env.age}</b><span>AGE</span></div><div><b>{env.role}</b><span>ROLE</span></div><div><b>{env.gender}</b><span>GENDER</span></div><div><b>{env.location}</b><span>LOCATION</span></div><div><b>—</b><span>ORBS</span></div></div><div className="accountAge"><div><b>{accountDays===null?"—":accountDays.toLocaleString()}</b><span>DAYS ON DISCORD</span></div><div><b>{createdAt?createdAt.toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"}):"—"}</b><span>ACCOUNT CREATED</span></div></div><div className="profileLine"/><div className="miniRow"><span>Discord ID</span><button onClick={copy}>{copied?"Copied ✓":env.discordId||"Set ID"}</button></div></div>
  </section>
  <section id="about" className="section"><div className="sectionTitle"><span>01</span><div><p>ABOUT ME</p><h2>A little bit about what I build.</h2></div></div><div className="aboutBig"><div className="aboutText"><p>I&apos;m <b>{name}</b>, a coder and digital creator who likes building things people can actually use.</p><p>My work sits between <b>code, websites, Discord and Minecraft</b>. I enjoy taking an idea from a blank page to a polished, working experience.</p><p>From custom Discord communities and Minecraft servers to websites, automation and authorized server cloning tools, I care about the details that make a project feel complete.</p></div><div className="quote">“<br/><strong>Build it.<br/>Break it.<br/>Improve it.</strong><br/><span>— the process</span></div></div></section>
  <section id="skills" className="section"><div className="sectionTitle"><span>02</span><div><p>WHAT I DO</p><h2>Things I build.</h2></div></div><div className="skillGrid"><article className="skillCard"><div className="skillIcon"><Icon kind="code"/></div><small>01</small><h3>Coding & Development</h3><p>Tools, systems, automation and projects built with code.</p></article><article className="skillCard"><div className="skillIcon"><Icon kind="code"/></div><small>02</small><h3>Website Development</h3><p>Modern responsive websites with clean UI and interactive experiences.</p></article><article className="skillCard"><div className="skillIcon"><Icon kind="discord"/></div><small>03</small><h3>Discord Development</h3><p>Server structure, roles, permissions, automation and communities.</p></article><article className="skillCard"><div className="skillIcon"><Icon kind="minecraft"/></div><small>04</small><h3>Minecraft Development</h3><p>Server configuration, gameplay systems, ranks, plugins and networks.</p></article><article className="skillCard"><div className="skillIcon">◈</div><small>05</small><h3>Discord Server Cloning</h3><p>Authorized server structure migration and backup tooling.</p></article><article className="skillCard"><div className="skillIcon">✦</div><small>06</small><h3>Ideas & Experiments</h3><p>Trying new concepts, designs and technologies to build something different.</p></article></div></section>
  <section id="socials" className="section"><div className="sectionTitle"><span>03</span><div><p>FIND ME</p><h2>Across the internet.</h2></div></div><div className="socialGrid">{socials.map(([title,url,kind])=><a className="social" key={title} href={url} target="_blank" rel="noreferrer"><span className="socialIcon"><Icon kind={kind}/></span><span><small>SOCIAL</small><strong>{title}</strong></span><b>↗</b></a>)}</div></section>
  <footer><span>© {new Date().getFullYear()} {env.name}. Built with code & curiosity.</span><button onClick={copy}>{copied?"Copied":"Copy Discord ID"}</button></footer>
  <div className="bottomStatus"><div className="bottomAvatarWrap"><img src={image} alt=""/><span className={`bottomDot ${status}`}/>{decorationImage&&<img className="bottomDecoration" src={decorationImage} alt=""/>}</div><div className="bottomText"><strong>{name}</strong><span>{username} · <i className={`tinyStatus ${status}`}/>{labels[status]}</span></div><div className="bottomOrb">◈ —</div><button className="bottomDiscord" onClick={copy}><Icon kind="discord"/></button></div>
 </main>;
}
